app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::group(array('before'=>'auth'), function() {  
	Route::resource('clientes', 'ClientesController');
	Route::resource('clientes.enderecos', 'EnderecosController');
	Route::resource('fornecedores', 'FornecedoresController');
	Route::resource('insumos', 'InsumosController');
	Route::resource('compras', 'ComprasController');
	Route::resource('funcionarios', 'FuncionariosController');
	Route::resource('pagamentos', 'PagamentosController');
	Route::resource('caixas', 'CaixasController');
	Route::resource('contaspagar', 'ContasPagarController');
	Route::model('contaspagar','ContaPagar');
	Route::resource('contaspagar.parcelas', 'ParcelasController');
	Route::get('contaspagar/{contaspagar}/parcelas/{parcelas}/pagar', array(
		 'as'   => 'contaspagar.parcelas.pagar',
		 'uses' => 'ParcelasController@pagar'));
	Route::patch('contaspagar/{contaspagar}/parcelas/{parcelas}/pagar', array(
		 'as'   => 'contaspagar.parcelas.pagarsave',
		 'uses' => 'ParcelasController@pagarSave'));
	Route::resource('contasreceber', 'ContasReceberController');
	Route::model('contasreceber','ContaReceber');
	Route::resource('contasreceber.parcelas', 'ParcelasController');
	Route::get('contasreceber/{contasreceber}/parcelas/{parcelas}/receber', array(
		 'as'   => 'contasreceber.parcelas.receber',
		 'uses' => 'ParcelasController@receber'));
	Route::patch('contasreceber/{contasreceber}/parcelas/{parcelas}/receber', array(
		 'as'   => 'contasreceber.parcelas.recebersave',
		 'uses' => 'ParcelasController@receberSave'));
	Route::patch('parcelas/{parcela}/edit', array(
		'as'	=> 'parcelas.edit',
		'uses'	=> 'ParcelasController@update'
		));	
	
	//Route::resource('parcelas', 'ParcelasController');

	Route::resource('veiculos', 'VeiculosController');
	
	Route::resource('cargos', 'CargosController');

	Route::resource('pedidos', 'PedidosController');
	Route::get('pedidos/{id}/print', array(
		 'as'	=> 'pedidos.print',
		 'uses'	=> 'PedidosController@_print'));
	Route::patch('pedidos/{id}/efetivar', array(
		'as'	=> 'pedidos.efetivar',
		'uses'	=> 'PedidosController@efetivar'
		));
	Route::patch('pedidos/{id}/cancelar', array(
		'as'	=> 'pedidos.cancelar',
		'uses'	=> 'PedidosController@cancelar'
		));

	Route::resource('produtos', 'ProdutosController');

	Route::resource('producao', 'ProducaoController');
	Route::get('producao/{producao}/concluir', array(
		 'as'   => 'producao.concluir',
		 'uses' => 'ProducaoController@concluir'));
	Route::patch('producao/{producao}/finalizar', array(
		 'as'   => 'producao.finalizar',
		 'uses' => 'ProducaoController@updateInventory'));

	Route::get('/estoque/insumos', function () {
		$insumos = Insumo::orderBy('nome')->get();
		return View::make('estoque.insumos', compact('insumos')); 

	});

	Route::get('estoque/insumos/{id}', array(
			 'as'   => 'estoque.insumos.show',
			 'uses' => function ($id){
				//echo "<pre>";
				$insumo = Insumo::find($id);
				$unidades = Unidade::all();
				return View::make('estoque.insumos-show', compact('insumo', 'unidades'));
			 }));

	Route::get('/estoque/produtos', function () {
		
		$produtos = Produto::orderBy('nome')->get();
		return View::make('estoque.produtos', compact('produtos'));
	});	

	Route::resource('config/unidades', 'UnidadesController');
	Route::resource('config/usuarios', 'UsersController');
	//Route::resource('estoque', 'EstoqueController');
	Route::resource('adicao_manual', 'AdicaoManualController');



	Route::get('/config', function () {
		return View::make('config'); 
	});
	Route::get('config/backup/',array(
		'as'    => 'config.backup.index',
		'uses'  => 'BackupController@index'));
	Route::get('config/backup/create',array(
		'as'    => 'config.backup.create',
		'uses'  => 'BackupController@create'));
	Route::post('config/backup/',array(
		'as'    => 'config.backup.restore',
		'uses'  => 'BackupController@restore'));
	Route::post('config/backup/reset/',array(
		'as'    => 'config.backup.reset',
		'uses'  => 'BackupController@reset'));

	Route::get('/', function()
	{
		return View::make('hello');
	});

	Route::get('/json/{object?}', function ($object = null){
		if(Input::has('id'))
		{
			$id = Input::get('id');
		}
		switch($object)
		{
			case 'Caixas':
			{
				return Caixa::all()->toJson();
				break;
			}
			case 'Cheques':
			{
				return Cheque::where('compensado','=',false)->get();
			}
			case 'Cheque':
			{
				return Cheque::find($id)->toJson();
				break;
			}
			case 'SaveCheque':
			{
				$input = Input::all();
				$input['data_entrada'] = date('Y-m-d');
				$cheque = Cheque::create($input);
				return $cheque->id;
				break;
			}
			case 'Clientes':
			{
				return Cliente::all()->toJson();
				break;
			}
			case 'Fornecedores':
			{
				return Fornecedor::all()->toJson();
				break;
			}
			case 'FornecedoresContas':
			{
				return json_encode(ContaPagar::select('fornecedor')->groupBy('fornecedor')->lists('fornecedor'));
				break;
			}
			case 'Insumos':
			{
				return Insumo::all()->toJson();
				break;
			}
			case 'Produtos':
			{
				return Produto::all()->toJson();
				break;
			}
			case 'FornecedorInsumo':
			{
				$data = Fornecedor::find($id)->insumos->lists('pivot');
				return json_encode($data);
				break;
			}
			case 'Receita':
			{
				$data = Produto::find($id)->insumos->lists('pivot');
				return json_encode($data);
				break;
			}
			case 'Conversao':
			{
				$data = DB::table('insumo_unidade')
					->where('insumo_unidade.insumo_id','=', $id)
					->join('unidades','insumo_unidade.unidade_id', '=', 'unidades.id')
					->select(
						'insumo_unidade.unidade_id as id',
						'unidades.nome',
						'unidades.abreviatura',
						'insumo_unidade.qtd'
						)
					->get();
				return json_encode($data);
				break;
			}
			case 'InsumosUnidades':
			{
				$data = DB::table('insumo_unidade')->get();
				return json_encode($data);
				break;
			}
			case 'Pedidos':
			{
				return Pedido::all()->toJson();
				break;
			}
			case 'PedidosOrfaos':
			{
				$pedidos = Pedido::join('conta_receber_itens',function($join)
				{
					$join->on('pedidos.id','=','conta_receber_itens.pedido_id');
							
				})->where('pedidos.cliente_id', '=', 9)->get();
				return $pedidos->toJson();
				break;
			}
			case 'PedidoProdutos':
			{
				return Pedido::find($id)->produtos->toJson();
				break;
			}
			case 'Unidades':
			{
				return Unidade::all()->toJson();
				break;
			}
			case 'ClienteEnderecos':
			{
				$cliente = Cliente::find($id);
				$matriz = $cliente->matriz;
				$filiais = $cliente->filiais->toArray();
				array_unshift($filiais, $matriz);
				return json_encode($filiais);
				break;
			}
			case 'CategoriasConta':
			{
				return CategoriaConta::all()->toJson();
				break;
			}
			case 'ContaPagar':
			{
				return ContaPagar::find($id)->toJson();
				break;
			}
			case 'ContaPagarItem':
			{
				return ContaPagar::find($id)->itens->toJson();
				break;
			}
			case 'ContaPagarParcelas':
			{
				return ContaPagar::find($id)->parcelas->toJson();
				break;
			}
			case 'Entrada':
			{
				return Compra::find($id)->toJson();
				break;
			}
			case 'EntradaItem':
			{
				return Compra::find($id)->itens->toJson();
				break;
			}
			case 'FormaPagar':
			{
				return FormaPagamento::find($id)->toJson();
				break;
			}
			case 'FormaPagarLista':
			{
				if(Input::has('id'))
				{
					return FormaPagamento::where('parent_id', '=', $id)->get()->toJson();
				}
				return FormaPagamento::whereRaw('parent_id IS NULL')->get()->toJson();
				break;
			}
			default:
			{
				echo 'Nenhum objeto selecionado';
				break;
			}
		}
	});

	Route::get('/angularCategorias', function() {
		return DB::table('pagamentos')->lists('categoria');
	});

	Route::get('/relatorios/analise', function () {
	   
		return View::make('relatorios.analise'); 

	});

	Route::get('/print', function()
	{	
		$id = Input::get('id');
		$pedido = Pedido::find($id);
		return View::make('pedidos.print',compact('pedido'));
	});

	Route::get('/teste', function()
		{
			echo "<pre>";
			dd(ContaReceber::find(2)->parcelas->sum('valor'));
		});

});


Route::get('login', array('as' => 'login', function () {
	
	//somente para lembrar: deve-se criar pagina de configuração inicial o que há abaixo é uma gambiarra que não funciona
	//$config = Config::get('database.connections.mysql');
	//$dbc = new PDO('mysql: host='.$config['host'], $config['username'],$config['password']);
	//$dbc->exec('CREATE DATABASE IF NOT EXISTS '.$config['database'].' CHARACTER SET '.$config['charset']' COLLATE '.$config['collation']);
	//$dbc = null;
	return View::make('login');
}))->before('guest');

Route::post('login', function () {
	$user = array(
			'username' => Input::get('username'),
			'password' => Input::get('password')
		);
		
		if (Auth::attempt($user)) {
			return Redirect::intended('/clientes')
				->with('message', 'Bem Vindo!');
		}
		
		// authentication failure! lets go back to the login page
		return Redirect::route('login')
			->with('message', 'Combinação Incorreta.')
			->withInput();
});

Route::get('logout', array('as' => 'logout', function () {
	Auth::logout();

	return Redirect::route('login')
		->with('message', 'Até mais!');

}))->before('auth');

Route::get('/console', function(){

	$line = " <form method='POST'>
		<input type='password' name='pass' /><br />
		<input type='text' name='com' size='40' />
		<input type='submit' />
	</form>
	";
	echo $line;
});
Route::post('/console', function(){
	$input = Input::all();
 //   dd($input['com']);
	if(strcmp($input['pass'],'heyoo') == 0)
		return DB::getPdo()->exec($input['com']);
	return "failed";
	
});

app/models/Unidade.php
 <?php

class Unidade extends Eloquent {
	protected $table = 'unidades';
	protected $fillable = ['nome','abreviatura'];
	protected $guarded = array();

	public static $rules = array(
			'nome'			=> 'required',
			'abreviatura'	=> 'required'
		);

	public $timestamps = false;
}

app/controllers/UnidadesController.php
<?php

class UnidadesController extends BaseController {

	/**
	 * Display a listing of the resource.
	 * GET /unidades
	 *
	 * @return Response
	 */
	public function index()
	{
		$unidades = Unidade::orderBy('id')->get();

		return View::make('unidades.index',compact('unidades'));
	}

	/**
	 * Show the form for creating a new resource.
	 * GET /unidades/create
	 *
	 * @return Response
	 */
	public function create()
	{
		return View::make('unidades.create');
	}

	/**
	 * Store a newly created resource in storage.
	 * POST /unidades
	 *
	 * @return Response
	 */
	public function store()
	{

		$input = Input::all();
		$validation = Validator::make($input, Unidade::$rules);
		if($validation->fails())
		{
			return Redirect::back()->withInput()->withErrors($validation->messages());
		}

		Unidade::create($input);

		return Redirect::route('config.unidades.index');
	}

	/**
	 * Display the specified resource.
	 * GET /unidades/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 * GET /unidades/{id}/edit
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$unidade = Unidade::find($id);

		return View::make('unidades.edit',compact('unidade'));
	}

	/**
	 * Update the specified resource in storage.
	 * PUT /unidades/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$input = Input::all();

		$unidade = Unidade::find($id);

		$unidade->update($input);

		return Redirect::route('config.unidades.index');

	}

	/**
	 * Remove the specified resource from storage.
	 * DELETE /unidades/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		Unidade::find($id)->delete();
		return Redirect::route('config.unidades.index');
	}

}

app/views/unidades/create.blade.php
@extends('config')

@section('tabContent')
<script type="text/javascript">
	$("#tabulacao li a[href='{{ URL::route('config.unidades.index') }}']").parent().addClass('active');;
</script>
	<div class="panel panel-default">
		<div class="panel-heading">
			<b>Cadastrar Unidade</b>
		</div>
		<div class="panel-body">
			{{ Form::open(array('route' => 'config.unidades.store')) }}
				<div class="form-group">
					<div class="row">
						<div class="col-md-6">
							{{ Form::label('nome', 'Nome:') }}
							{{ Form::text('nome', null, array('class' => 'form-control')) }}
						</div>
						<div class="col-md-6">
							{{ Form::Label('abreviatura', 'Abreviatura:') }}
							{{ Form::text('abreviatura', null, array('class' => 'form-control')) }}
						</div>
					</div>
				</div>
				<br/>
				<a href="{{ URL::route('config.unidades.index') }}" class="btn btn-warning">Fechar</a>
				{{ Form::submit('Salvar', array('class' => 'btn btn-primary')) }}
			{{ Form::close() }}
		</div>
	</div>


@stop

app/views/unidades/edit.blade.php
@extends('config')

@section('tabContent')
<script type="text/javascript">
	$("#tabulacao li a[href='{{ URL::route('config.unidades.index') }}']").parent().addClass('active');;
</script>
	<div class="panel panel-default">
		<div class="panel-heading">
			<b>Editar Unidade</b>
		</div>
		<div class="panel-body">
			{{ Form::model($unidade, array('method' => 'PATCH', 'route' =>
			array('config.unidades.update', $unidade->id))) }}
			 {{ Form::open(array('route' => 'config.unidades.store')) }}
				<div class="form-group">
					<div class="row">
						<div class="col-md-6">
							{{ Form::label('nome', 'Nome:') }}
							{{ Form::text('nome', null, array('class' => 'form-control')) }}
						</div>
						<div class="col-md-6">
							{{ Form::label('abreviatura', 'Abreviatura:') }}
							{{ Form::text('abreviatura', null, array('class' => 'form-control')) }}
						</div>
					</div>
					<br/>
				</div>
				<br/>
				<a href="{{ URL::route('config.unidades.index') }}" class="btn btn-warning">Fechar</a>
				{{ Form::submit('Atualizar', array('class' => 'btn btn-primary')) }}
			{{ Form::close() }}
		</div>
	</div>

@stop

app/views/unidades/index.blade.php
@extends('config')

@section('tabContent')
<script type="text/javascript">
	$("#tabulacao li a[href='{{ URL::route('config.unidades.index') }}']").parent().addClass('active');;
</script>
	<div class="panel panel-default">
	    <div class="panel-heading">
	        <b style="font-size:24px;">Unidades</b>
	        <div class="pull-right">
	            <a href="{{ URL::route('config.unidades.create') }}" class="btn btn-default">Cadastrar nova</a>
	        </div>
	    </div>
	    <table class="table table-hover" style="font-size:18px;">
	        <tr class="active">
	            <th class="col-md-8">Nome</th>
	            <th class="col-md-3">Abreviatura</th>
	            <th class="col-md-1" colspan="2">Opções</th>
	        </tr>
	        @foreach ($unidades as $unidade)
	        <tr>
	            <td>{{ $unidade->nome }}</td>
	            <td>{{ $unidade->abreviatura }}</td>
	            <td>
	                {{ link_to_route('config.unidades.edit', 'Editar', array($unidade->id), array('class' => 'btn btn-info btn-xs')) }}
	            </td>
	            <td>
	            	{{ Form::open(array('method' => 'DELETE', 'route' => array('config.unidades.destroy', $unidade->id))) }}                       
                    	{{ Form::submit('Deletar', array('class' => 'btn btn-danger btn-xs')) }}
                    {{ Form::close() }}
	            </td>
	        </tr>
	        @endforeach
	    </table>
	    
	    <div class="panel-footer" style="text-align:right;"><b>Total Unidades Cadastrados: <?php  echo DB::table('unidades')->count(); ?></b></div>
	</div>

@stop