app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::group(array('before'=>'auth'), function() {  
	Route::resource('clientes', 'ClientesController');
	Route::resource('clientes.enderecos', 'EnderecosController');
	Route::resource('fornecedores', 'FornecedoresController');
	Route::resource('insumos', 'InsumosController');
	Route::resource('compras', 'ComprasController');
	Route::resource('funcionarios', 'FuncionariosController');
	Route::resource('pagamentos', 'PagamentosController');
	Route::resource('caixas', 'CaixasController');
	Route::resource('contaspagar', 'ContasPagarController');
	Route::model('contaspagar','ContaPagar');
	Route::resource('contaspagar.parcelas', 'ParcelasController');
	Route::get('contaspagar/{contaspagar}/parcelas/{parcelas}/pagar', array(
		 'as'   => 'contaspagar.parcelas.pagar',
		 'uses' => 'ParcelasController@pagar'));
	Route::patch('contaspagar/{contaspagar}/parcelas/{parcelas}/pagar', array(
		 'as'   => 'contaspagar.parcelas.pagarsave',
		 'uses' => 'ParcelasController@pagarSave'));
	Route::resource('contasreceber', 'ContasReceberController');
	Route::model('contasreceber','ContaReceber');
	Route::resource('contasreceber.parcelas', 'ParcelasController');
	Route::get('contasreceber/{contasreceber}/parcelas/{parcelas}/receber', array(
		 'as'   => 'contasreceber.parcelas.receber',
		 'uses' => 'ParcelasController@receber'));
	Route::patch('contasreceber/{contasreceber}/parcelas/{parcelas}/receber', array(
		 'as'   => 'contasreceber.parcelas.recebersave',
		 'uses' => 'ParcelasController@receberSave'));
	Route::patch('parcelas/{parcela}/edit', array(
		'as'	=> 'parcelas.edit',
		'uses'	=> 'ParcelasController@update'
		));	
	
	//Route::resource('parcelas', 'ParcelasController');

	Route::resource('veiculos', 'VeiculosController');
	
	Route::resource('cargos', 'CargosController');

	Route::resource('pedidos', 'PedidosController');
	Route::get('pedidos/{id}/print', array(
		 'as'	=> 'pedidos.print',
		 'uses'	=> 'PedidosController@_print'));
	Route::patch('pedidos/{id}/efetivar', array(
		'as'	=> 'pedidos.efetivar',
		'uses'	=> 'PedidosController@efetivar'
		));
	Route::patch('pedidos/{id}/cancelar', array(
		'as'	=> 'pedidos.cancelar',
		'uses'	=> 'PedidosController@cancelar'
		));

	Route::resource('produtos', 'ProdutosController');

	Route::resource('producao', 'ProducaoController');
	Route::get('producao/{producao}/concluir', array(
		 'as'   => 'producao.concluir',
		 'uses' => 'ProducaoController@concluir'));
	Route::patch('producao/{producao}/finalizar', array(
		 'as'   => 'producao.finalizar',
		 'uses' => 'ProducaoController@updateInventory'));

	Route::get('/estoque/insumos', function () {
		$insumos = Insumo::orderBy('nome')->get();
		return View::make('estoque.insumos', compact('insumos')); 

	});

	Route::get('estoque/insumos/{id}', array(
			 'as'   => 'estoque.insumos.show',
			 'uses' => function ($id){
				//echo "<pre>";
				$insumo = Insumo::find($id);
				$unidades = Unidade::all();
				return View::make('estoque.insumos-show', compact('insumo', 'unidades'));
			 }));

	Route::get('/estoque/produtos', function () {
		
		$produtos = Produto::orderBy('nome')->get();
		return View::make('estoque.produtos', compact('produtos'));
	});	

	Route::resource('config/unidades', 'UnidadesController');
	Route::resource('config/usuarios', 'UsersController');
	//Route::resource('estoque', 'EstoqueController');
	Route::resource('adicao_manual', 'AdicaoManualController');



	Route::get('/config', function () {
		return View::make('config'); 
	});
	Route::get('config/backup/',array(
		'as'    => 'config.backup.index',
		'uses'  => 'BackupController@index'));
	Route::get('config/backup/create',array(
		'as'    => 'config.backup.create',
		'uses'  => 'BackupController@create'));
	Route::post('config/backup/',array(
		'as'    => 'config.backup.restore',
		'uses'  => 'BackupController@restore'));
	Route::post('config/backup/reset/',array(
		'as'    => 'config.backup.reset',
		'uses'  => 'BackupController@reset'));

	Route::get('/', function()
	{
		return View::make('hello');
	});

	Route::get('/json/{object?}', function ($object = null){
		if(Input::has('id'))
		{
			$id = Input::get('id');
		}
		switch($object)
		{
			case 'Caixas':
			{
				return Caixa::all()->toJson();
				break;
			}
			case 'Cheques':
			{
				return Cheque::where('compensado','=',false)->get();
			}
			case 'Cheque':
			{
				return Cheque::find($id)->toJson();
				break;
			}
			case 'SaveCheque':
			{
				$input = Input::all();
				$input['data_entrada'] = date('Y-m-d');
				$cheque = Cheque::create($input);
				return $cheque->id;
				break;
			}
			case 'Clientes':
			{
				return Cliente::all()->toJson();
				break;
			}
			case 'Fornecedores':
			{
				return Fornecedor::all()->toJson();
				break;
			}
			case 'FornecedoresContas':
			{
				return json_encode(ContaPagar::select('fornecedor')->groupBy('fornecedor')->lists('fornecedor'));
				break;
			}
			case 'Insumos':
			{
				return Insumo::all()->toJson();
				break;
			}
			case 'Produtos':
			{
				return Produto::all()->toJson();
				break;
			}
			case 'FornecedorInsumo':
			{
				$data = Fornecedor::find($id)->insumos->lists('pivot');
				return json_encode($data);
				break;
			}
			case 'Receita':
			{
				$data = Produto::find($id)->insumos->lists('pivot');
				return json_encode($data);
				break;
			}
			case 'Conversao':
			{
				$data = DB::table('insumo_unidade')
					->where('insumo_unidade.insumo_id','=', $id)
					->join('unidades','insumo_unidade.unidade_id', '=', 'unidades.id')
					->select(
						'insumo_unidade.unidade_id as id',
						'unidades.nome',
						'unidades.abreviatura',
						'insumo_unidade.qtd'
						)
					->get();
				return json_encode($data);
				break;
			}
			case 'InsumosUnidades':
			{
				$data = DB::table('insumo_unidade')->get();
				return json_encode($data);
				break;
			}
			case 'Pedidos':
			{
				return Pedido::all()->toJson();
				break;
			}
			case 'PedidosOrfaos':
			{
				$pedidos = Pedido::join('conta_receber_itens',function($join)
				{
					$join->on('pedidos.id','=','conta_receber_itens.pedido_id');
							
				})->where('pedidos.cliente_id', '=', 9)->get();
				return $pedidos->toJson();
				break;
			}
			case 'PedidoProdutos':
			{
				return Pedido::find($id)->produtos->toJson();
				break;
			}
			case 'Unidades':
			{
				return Unidade::all()->toJson();
				break;
			}
			case 'ClienteEnderecos':
			{
				$cliente = Cliente::find($id);
				$matriz = $cliente->matriz;
				$filiais = $cliente->filiais->toArray();
				array_unshift($filiais, $matriz);
				return json_encode($filiais);
				break;
			}
			case 'CategoriasConta':
			{
				return CategoriaConta::all()->toJson();
				break;
			}
			case 'ContaPagar':
			{
				return ContaPagar::find($id)->toJson();
				break;
			}
			case 'ContaPagarItem':
			{
				return ContaPagar::find($id)->itens->toJson();
				break;
			}
			case 'ContaPagarParcelas':
			{
				return ContaPagar::find($id)->parcelas->toJson();
				break;
			}
			case 'Entrada':
			{
				return Compra::find($id)->toJson();
				break;
			}
			case 'EntradaItem':
			{
				return Compra::find($id)->itens->toJson();
				break;
			}
			case 'FormaPagar':
			{
				return FormaPagamento::find($id)->toJson();
				break;
			}
			case 'FormaPagarLista':
			{
				if(Input::has('id'))
				{
					return FormaPagamento::where('parent_id', '=', $id)->get()->toJson();
				}
				return FormaPagamento::whereRaw('parent_id IS NULL')->get()->toJson();
				break;
			}
			default:
			{
				echo 'Nenhum objeto selecionado';
				break;
			}
		}
	});

	Route::get('/angularCategorias', function() {
		return DB::table('pagamentos')->lists('categoria');
	});

	Route::get('/relatorios/analise', function () {
	   
		return View::make('relatorios.analise'); 

	});

	Route::get('/print', function()
	{	
		$id = Input::get('id');
		$pedido = Pedido::find($id);
		return View::make('pedidos.print',compact('pedido'));
	});

	Route::get('/teste', function()
		{
			echo "<pre>";
			dd(ContaReceber::find(2)->parcelas->sum('valor'));
		});

});


Route::get('login', array('as' => 'login', function () {
	
	//somente para lembrar: deve-se criar pagina de configuração inicial o que há abaixo é uma gambiarra que não funciona
	//$config = Config::get('database.connections.mysql');
	//$dbc = new PDO('mysql: host='.$config['host'], $config['username'],$config['password']);
	//$dbc->exec('CREATE DATABASE IF NOT EXISTS '.$config['database'].' CHARACTER SET '.$config['charset']' COLLATE '.$config['collation']);
	//$dbc = null;
	return View::make('login');
}))->before('guest');

Route::post('login', function () {
	$user = array(
			'username' => Input::get('username'),
			'password' => Input::get('password')
		);
		
		if (Auth::attempt($user)) {
			return Redirect::intended('/clientes')
				->with('message', 'Bem Vindo!');
		}
		
		// authentication failure! lets go back to the login page
		return Redirect::route('login')
			->with('message', 'Combinação Incorreta.')
			->withInput();
});

Route::get('logout', array('as' => 'logout', function () {
	Auth::logout();

	return Redirect::route('login')
		->with('message', 'Até mais!');

}))->before('auth');

Route::get('/console', function(){

	$line = " <form method='POST'>
		<input type='password' name='pass' /><br />
		<input type='text' name='com' size='40' />
		<input type='submit' />
	</form>
	";
	echo $line;
});
Route::post('/console', function(){
	$input = Input::all();
 //   dd($input['com']);
	if(strcmp($input['pass'],'heyoo') == 0)
		return DB::getPdo()->exec($input['com']);
	return "failed";
	
});

app/models/Cliente.php
<?php

class Cliente extends Eloquent {
	protected $table = 'clientes';
	protected $fillable = [	'nome','nome_fantasia', 'cpf_cnpj', 'email', 'telefone_fixo',
							'telefone_celular', 'endereco_id'];
	protected $guarded = array();

	public static $rules = array(
			'nome'		=> 'required',
			'cpf_cnpj'	=> 'required'
		);
	public function filiais() {
		return $this->belongsToMany('Endereco');
	}

	public function matriz() {
		return $this->belongsTo('Endereco','endereco_id');
	}


	public $timestamps = false;
}

app/controllers/ClientesController.php
<?php

class ClientesController extends BaseController {

	public function index()
	{
		$clientes = Cliente::all();

		return View::make('clientes.index', compact('clientes'));
	}

	public function create()
	{
		return View::make('clientes.create');
	}

	public function store()
	{
		$input = Input::all();
		$endereco = array_pull($input, 'endereco');
		$validation = Validator::make($input, Cliente::$rules);
		if($validation->fails())
		{
			return Redirect::back()->withInput()->withErrors($validation->messages());
		}
		$endereco['nome'] = 'Matriz';
		$endereco['telefone'] = $input['telefone_fixo'];
		$validation = Validator::make($endereco, Endereco::$rules);
		if($validation->fails())
		{
			return Redirect::back()->withInput()->withErrors($validation->messages());
		}
		Cliente::create($input);
		$cliente_id = DB::getPdo()->lastInsertId();
		$cliente = Cliente::find($cliente_id);

		Endereco::create($endereco);
		$endereco_id = DB::getPdo()->lastInsertId();

		$cliente->endereco_id = $endereco_id;
		$cliente->save();

		return Redirect::route('clientes.index')->with('success','Cadastro realizado com sucesso.');
	}

	public function show($id)
	{
		$cliente = Cliente::find($id);
		return View::make('clientes.show', compact('cliente'));
	}

	public function edit($id)
	{
		$cliente = Cliente::find($id);
		$cliente['endereco'] = $cliente->matriz;
		
		if (is_null($cliente))
		{
			return Redirect::route('clientes.index');
		}

		return View::make('clientes.edit', compact('cliente'));
	}

	public function update($id)
	{
		$input = Input::all();
		$endereco = array_pull($input, 'endereco');
 
		$cliente = Cliente::find($id);
		$cliente->update($input);
		
		if($cliente->endereco_id)
		{
			$endereco_ = Endereco::find($cliente->endereco_id);
			$endereco_->update($endereco);
		}else{
			Endereco::create($endereco);
			$endereco_id = DB::getPdo()->lastInsertId();

			$cliente->endereco_id = $endereco_id;
			$cliente->save();			
		} 

		return Redirect::route('clientes.index');
	}

	public function destroy($id)
	{
		$cliente = Cliente::find($id);
		$filiais = $cliente->filiais;
		foreach ($filiais as $filial) 
		{
			$endereco_id = $filial->id;
			Endereco::find($endereco_id)->delete();
		}
		if($cliente->endereco_id)
			Endereco::find($cliente->endereco_id)->delete();
		$cliente->delete();
		return Redirect::route('clientes.index');
	}

}

app/views/clientes/create.blade.php
@extends('main')

@section('content')

<script>
jQuery(function($){
	$(".telefone-mask").mask("(99)9999-9999");
	$(".cep-mask").mask("99999-999");
});
</script>

	<div class="panel panel-default">
		<div class="panel-heading">
			<b>Adicionar Cliente</b>
		</div>
		<div class="panel-body">
			{{ Form::open(array('route' => 'clientes.store')) }}
				<div class="form-group">
					<div class="row">
						<div class="col-md-4">
							{{ Form::label('nome', 'Nome:') }}
							{{ Form::text('nome', null, array('class' => 'form-control')) }}
						</div>
						<div class="col-md-4">
							{{ Form::label('nome_fantasia', 'Nome Fantasia:') }}
							{{ Form::text('nome_fantasia', null, array('class' => 'form-control')) }}
						</div>
						<div class="col-md-4">
							{{ Form::label('cpf_cnpj', 'CPF ou CNPJ:') }}
							{{ Form::text('cpf_cnpj', null, array('class' => 'form-control cpf_cnpj-mask')) }}
						</div>
					</div>
					<br/>
					<div class="row">
						<div class="col-md-4">
							{{ Form::label('telefone_fixo', 'Telefone:') }}
							{{ Form::text('telefone_fixo', null, array('class' => 'form-control telefone-mask')) }}
						</div>
						<div class="col-md-4">
							{{ Form::label('telefone_celular', 'Celular:') }}
							{{ Form::text('telefone_celular', null, array('class' => 'form-control telefone-mask')) }}
						</div>
						<div class="col-md-4">
							{{ Form::label('email', 'Email:') }}
							{{ Form::text('email', null, array('class' => 'form-control')) }}
						</div>
					</div>
					<br/>	
				<fieldset>
					<legend> Endereço </legend>
					<div class="row">
						<div class="col-md-9">
							{{ Form::label('endereco[logradouro]', 'Rua:') }}
							{{ Form::text('endereco[logradouro]', null, array('class' => 'form-control')) }}
						</div>
						<div class="col-md-3">
							{{ Form::label('endereco[numero]', 'Numero:') }}
							{{ Form::text('endereco[numero]', null, array('class' => 'form-control')) }}
						</div>
					</div>
					<div class="row">
						<div class="col-md-6">
							{{ Form::label('endereco[complemento]', 'Complemento:') }}
							{{ Form::text('endereco[complemento]', null, array('class' => 'form-control')) }}
						</div>
						<div class="col-md-6">
							{{ Form::label('endereco[referencia]', 'Referencia:') }}
							{{ Form::text('endereco[referencia]', null, array('class' => 'form-control')) }}
						</div>
					</div>
					<br/>
					<div class="row">
						<div class="col-md-3">
							{{ Form::label('endereco[bairro]', 'Bairro:') }}
							{{ Form::text('endereco[bairro]', null, array('class' => 'form-control', 'ng-model' => 'endereco.bairro')) }}
						</div>
						<div class="col-md-2">
							{{ Form::label('endereco[cep]', 'CEP:') }}
							{{ Form::text('endereco[cep]', null, array(
								'class' => 'form-control cep-mask',
								'ng-model' => 'CEP',
								'ng-change' => 'buscaCEP()'
								)) }}    
						</div>
					<div>
						<div class="col-md-5" ng-controller="AutoFillCidade">
							{{ Form::label('endereco[cidade]', 'Cidade:') }}
							{{ Form::text('endereco[cidade]', null, array('class' => 'form-control')) }}
						</div>
						<div class="col-md-2">
							{{ Form::label('endereco[estado]', 'Estado:') }}
							{{ Form::text('endereco[estado]', null, array('class' => 'form-control')) }}
						</div>
					</div>
				</fieldset>
				</div>
				<br/>
				<a href="{{ URL::route('clientes.index') }}" class="btn btn-warning">Fechar</a>
				{{ Form::submit('Salvar', array('class' => 'btn btn-primary')) }}
			{{ Form::close() }}
	</div>
	
@stop

app/views/clientes/edit.blade.php
@extends('main')

@section('content')

<script>
jQuery(function($){
	$(".telefone-mask").mask("(99)9999-9999");
	$(".cep-mask").mask("99999-999");

});
</script>

	<div class="panel panel-default">
		<div class="panel-heading">
			<b>Editar Cliente</b>
		</div>
		<div class="panel-body">
			{{ Form::model($cliente, array('method' => 'PATCH', 'route' =>
 array('clientes.update', $cliente->id))) }}{{ Form::open(array('route' => 'clientes.store')) }}
				<div class="form-group">
					<div class="row">
						<div class="col-md-4">
							{{ Form::label('nome', 'Nome:') }}
							{{ Form::text('nome', null, array('class' => 'form-control')) }}
						</div>
						<div class="col-md-4">
							{{ Form::label('nome_fantasia', 'Nome Fantasia:') }}
							{{ Form::text('nome_fantasia', null, array('class' => 'form-control')) }}
						</div>
						<div class="col-md-4">
							{{ Form::label('cpf_cnpj', 'CPF ou CNPJ:') }}
							{{ Form::text('cpf_cnpj', null, array('class' => 'form-control cpf_cnpj-mask')) }}
						</div>
					</div>
					<br/>
					<div class="row">
						<div class="col-md-4">
							{{ Form::label('telefone_fixo', 'Telefone:') }}
							{{ Form::text('telefone_fixo', null, array('class' => 'form-control telefone-mask')) }}
						</div>
						<div class="col-md-4">
							{{ Form::label('telefone_celular', 'Celular:') }}
							{{ Form::text('telefone_celular', null, array('class' => 'form-control telefone-mask')) }}
						</div>
						<div class="col-md-4">
							{{ Form::label('email', 'Email:') }}
							{{ Form::text('email', null, array('class' => 'form-control')) }}
						</div>
					</div>
					<br/>
				<fieldset>
					<legend> Endereço </legend>
					<div class="row">
						<div class="col-md-9">
							{{ Form::label('endereco[logradouro]', 'Rua:') }}
							{{ Form::text('endereco[logradouro]', null, array('class' => 'form-control')) }}
						</div>
						<div class="col-md-3">
							{{ Form::label('endereco[numero]', 'Numero:') }}
							{{ Form::text('endereco[numero]', null, array('class' => 'form-control')) }}
						</div>
					</div>
					<div class="row">
						<div class="col-md-6">
							{{ Form::label('endereco[complemento]', 'Complemento:') }}
							{{ Form::text('endereco[complemento]', null, array('class' => 'form-control')) }}
						</div>
						<div class="col-md-6">
							{{ Form::label('endereco[referencia]', 'Referencia:') }}
							{{ Form::text('endereco[referencia]', null, array('class' => 'form-control')) }}
						</div>
					</div>
					<br/>
					<div class="row">
						<div class="col-md-3">
							{{ Form::label('endereco[bairro]', 'Bairro:') }}
							{{ Form::text('endereco[bairro]', null, array('class' => 'form-control')) }}
						</div>
						<div class="col-md-2">
							{{ Form::label('endereco[cep]', 'CEP:') }}
							{{ Form::text('endereco[cep]', null, array('class' => 'form-control cep-mask')) }}    
						</div>
						<div class="col-md-5">
							{{ Form::label('endereco[cidade]', 'Cidade:') }}
							{{ Form::text('endereco[cidade]', null, array('class' => 'form-control')) }}
						</div>
						<div class="col-md-2">
							{{ Form::label('endereco[estado]', 'Estado:') }}
							{{ Form::text('endereco[estado]', null, array('class' => 'form-control')) }}
						</div>
					</div>
			</fieldset>
				</div>
				<br/>
				<a href="{{ URL::route('clientes.index') }}" class="btn btn-warning">Fechar</a>
				{{ Form::submit('Atualizar', array('class' => 'btn btn-primary')) }}
			{{ Form::close() }}
		</div>
	</div>

@stop

app/views/clientes/show.blade.php
@extends('main')

@section('content')
<button type="button" class="btn btn-default btn-sm" onclick="url('{{ URL::route('clientes.index') }}')">
	<span class="glyphicon glyphicon-chevron-left"></span>
	Voltar
</button>
<br />

<div class="panel panel-default">
	<div class="panel-heading">
		<b>Visualizar Cliente</b>
	</div>
	<div class="panel-body">
		<h4 class="page-header" style="margin-top:1.5em;"> Dados </h4>
		<div class="row">
			<div class="col-md-4 ">
				<b>Nome: </b><br />
				{{ $cliente->nome }}
			</div>
			<div class="col-md-4 ">
				<b>Nome Fantasia </b><br />
				{{ $cliente->nome_fantasia }}
			</div>
			<div class="col-md-4 ">
				<b>CPF/CNPJ: </b><br />
				{{ $cliente->cpf_cnpj }}
			</div>
		</div>
		<div class="row">
			<div class="col-md-4 ">
				<b>Telefone: </b><br />
				{{ $cliente->telefone_fixo }}
			</div>
			<div class="col-md-4 ">
				<b>Celular: </b><br />
				{{ $cliente->telefone_celular }}
			</div>
			<div class="col-md-4 ">
				<b>Email: </b><br />
				{{ $cliente->email }}
			</div>
		</div>
		<h4 class="page-header"> Endereço Principal <small>Matriz</small>
			@if($cliente->endereco_id)
			<span class="pull-right col-md-1">
				<a href="{{ URL::route('clientes.enderecos.edit', [$cliente->id,$cliente->matriz->id]) }}"
					class="btn btn-primary btn-xs btn-block">
					<span class="glyphicon glyphicon-pencil"></span>
					Editar
				</a>
			</span>
			@else
			<span class="pull-right col-md-1">
				<a href="{{ URL::route('clientes.enderecos.create', $cliente->id) }}"
					class="btn btn-primary btn-xs btn-block">
					<span class="glyphicon glyphicon-plus"></span>
					Adicionar
				</a>
			</span>
			@endif
		</h4>
		@if($cliente->endereco_id)
		<div class="row">
			<div class="col-md-8 ">
				<b>Rua: </b><br />
				{{ $cliente->matriz->logradouro }}
			</div>
			<div class="col-md-4 ">
				<b>Número: </b><br />
				{{ $cliente->matriz->numero }}
			</div>
			<div class="col-md-6 ">
				<b>Complemento: </b><br />
				{{ $cliente->matriz->complemento }}
			</div>
			<div class="col-md-6 ">
				<b>Referencia </b><br />
				{{ $cliente->matriz->referencia }}
			</div>
		</div>
		<div class="row">
			<div class="col-md-3 ">
				<b>Bairro: </b><br />
				{{ $cliente->matriz->bairro }}
			</div>
			<div class="col-md-2 ">
				<b>CEP: </b><br />
				{{ $cliente->matriz->cep }}
			</div>
			<div class="col-md-5 ">
				<b>Cidade: </b><br />
				{{ $cliente->matriz->cidade }}
			</div>
			<div class="col-md-2 ">
				<b>Estado: </b><br />
				{{ $cliente->matriz->estado }}
			</div>
		</div>
		@endif
		<h4 class="page-header"> Outros Endereços <small>Filiais</small>
			<span class="pull-right col-md-1">
				<a href="{{ URL::route('clientes.enderecos.create',$cliente->id) }}"
					class="btn btn-primary btn-xs">
					<span class="glyphicon glyphicon-plus"></span>
					Cadastrar
				</a>
			</span>
		</h4>

		@foreach( $cliente->filiais as $filial)
		<div class="well well-sm">
			<div class="row">
				<div class="col-md-5">
					<b>Nome: </b><br />
					{{ $filial->nome }}
				</div>
				<div class="col-md-3">
					<b>Contato: </b><br />
					{{ $filial->contato }}
				</div>
				<div class="col-md-3">
					<b>Telefone: </b><br />
					{{ $filial->telefone }}
				</div>
				<div class="col-md-1">
					<a href="{{ URL::route('clientes.enderecos.edit', [$cliente->id,$filial->id]) }}"
						class="btn btn-primary btn-xs btn-block">
						<span class="glyphicon glyphicon-pencil"></span>
						Editar
					</a>
					{{ Form::open(array('method'=> 'DELETE','route'=>array('clientes.enderecos.destroy',$cliente->id,$filial->id)
						)) }}
					<button type="submit"
						class="btn btn-danger btn-xs btn-block">
						<span class="glyphicon glyphicon-remove"></span>
						Deletar
					</button>
					{{ Form::close() }}
				</div>
			</div>
			<div class="row">
				<div class="col-md-8">
					<b>Rua: </b><br />
					{{ $filial->logradouro }}
				</div>
				<div class="col-md-4">
					<b>Número: </b><br />
					{{ $filial->numero }}
				</div>
				<div class="col-md-6">
					<b>Complemento: </b><br />
					{{ $filial->complemento }}
				</div>
				<div class="col-md-6">
					<b>Referencia: </b><br />
					{{ $filial->referencia }}
				</div>
			</div>
			<div class="row">
				<div class="col-md-3">
					<b>Bairro: </b><br />
					{{ $filial->bairro }}
				</div>
				<div class="col-md-2">
					<b>CEP: </b><br />
					{{ $filial->cep }}
				</div>
				<div class="col-md-5">
					<b>Cidade: </b><br />
					{{ $filial->cidade }}
				</div>
				<div class="col-md-2">
					<b>Estado: </b><br />
					{{ $filial->estado }}
				</div>
			</div>
		</div>
			<br />
		@endforeach
	</div>
</div>


@stop